/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PricesRouteImport } from './routes/prices'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainingIndexRouteImport } from './routes/training/index'
import { Route as TrainingTrainingsRouteRouteImport } from './routes/training/_trainings/route'
import { Route as TrainingTrainingsBasicRouteImport } from './routes/training/_trainings/basic'

const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricesRoute = PricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingIndexRoute = TrainingIndexRouteImport.update({
  id: '/training/',
  path: '/training/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingTrainingsRouteRoute = TrainingTrainingsRouteRouteImport.update({
  id: '/training/_trainings',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingTrainingsBasicRoute = TrainingTrainingsBasicRouteImport.update({
  id: '/basic',
  path: '/basic',
  getParentRoute: () => TrainingTrainingsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/prices': typeof PricesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/training': typeof TrainingTrainingsRouteRouteWithChildren
  '/training/': typeof TrainingIndexRoute
  '/training/basic': typeof TrainingTrainingsBasicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/prices': typeof PricesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/training': typeof TrainingIndexRoute
  '/training/basic': typeof TrainingTrainingsBasicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/prices': typeof PricesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/training/_trainings': typeof TrainingTrainingsRouteRouteWithChildren
  '/training/': typeof TrainingIndexRoute
  '/training/_trainings/basic': typeof TrainingTrainingsBasicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/prices'
    | '/privacy-policy'
    | '/training'
    | '/training/'
    | '/training/basic'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/prices'
    | '/privacy-policy'
    | '/training'
    | '/training/basic'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/prices'
    | '/privacy-policy'
    | '/training/_trainings'
    | '/training/'
    | '/training/_trainings/basic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  PricesRoute: typeof PricesRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TrainingTrainingsRouteRoute: typeof TrainingTrainingsRouteRouteWithChildren
  TrainingIndexRoute: typeof TrainingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prices': {
      id: '/prices'
      path: '/prices'
      fullPath: '/prices'
      preLoaderRoute: typeof PricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/': {
      id: '/training/'
      path: '/training'
      fullPath: '/training/'
      preLoaderRoute: typeof TrainingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/_trainings': {
      id: '/training/_trainings'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingTrainingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/_trainings/basic': {
      id: '/training/_trainings/basic'
      path: '/basic'
      fullPath: '/training/basic'
      preLoaderRoute: typeof TrainingTrainingsBasicRouteImport
      parentRoute: typeof TrainingTrainingsRouteRoute
    }
  }
}

interface TrainingTrainingsRouteRouteChildren {
  TrainingTrainingsBasicRoute: typeof TrainingTrainingsBasicRoute
}

const TrainingTrainingsRouteRouteChildren: TrainingTrainingsRouteRouteChildren =
  {
    TrainingTrainingsBasicRoute: TrainingTrainingsBasicRoute,
  }

const TrainingTrainingsRouteRouteWithChildren =
  TrainingTrainingsRouteRoute._addFileChildren(
    TrainingTrainingsRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  PricesRoute: PricesRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TrainingTrainingsRouteRoute: TrainingTrainingsRouteRouteWithChildren,
  TrainingIndexRoute: TrainingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
